version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: 123klpym
      MYSQL_ROOT_PASSWORD: root987
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge